/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Formularios;

import hospital_arzobispo_loayza.g_A_asistencias;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class g_A_VentanaGestionAsistencias extends javax.swing.JDialog {
    private ArrayList<g_A_asistencias> listaAsistencias;
    
    FileWriter writer ;
    File File = new File("proyect_logs\\gestionAsistencia.txt");
    String nombreEmpleado;
    String apellidoEmpleado;
    String fecha;
    String turno;
    String horaEntrada;
    String horaSalida;
    /**
     * Creates new form NewJDialog
     */
    public g_A_VentanaGestionAsistencias() {
        initComponents();
        listaAsistencias = new ArrayList<>();
        jComboBoxTurno.removeAllItems();
        jComboBoxTurno.addItem("");
        jComboBoxTurno.addItem("Mañana");
        jComboBoxTurno.addItem("Noche");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        NEmpleado = new javax.swing.JLabel();
        jTextFieldNE = new javax.swing.JTextField();
        AEmpleado = new javax.swing.JLabel();
        jTextFieldAE = new javax.swing.JTextField();
        Fecha = new javax.swing.JLabel();
        Turno = new javax.swing.JLabel();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        HoraEntrada = new javax.swing.JLabel();
        jTextFieldHentrada = new javax.swing.JTextField();
        HoraSalida = new javax.swing.JLabel();
        jTextFieldHsalida = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Gestion Asistencias");

        NEmpleado.setText("Nombre Empleado:");

        AEmpleado.setText("Apellido Empleado:");

        Fecha.setText("Turno:");

        Turno.setText("Fecha:");

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTurnoActionPerformed(evt);
            }
        });

        HoraEntrada.setText("Hora Entrada:");

        jTextFieldHentrada.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldHentrada.setText("00:00");
        jTextFieldHentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldHentradaMousePressed(evt);
            }
        });

        HoraSalida.setText("Hora Salida:");

        jTextFieldHsalida.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldHsalida.setText("00:00");
        jTextFieldHsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldHsalidaMousePressed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jTextFieldFecha.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldFecha.setText("dd/mm/aaaa");
        jTextFieldFecha.setToolTipText("");
        jTextFieldFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldFechaMousePressed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Title)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(NEmpleado)
                            .addGap(16, 16, 16)
                            .addComponent(jTextFieldNE, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(AEmpleado)
                            .addGap(14, 14, 14)
                            .addComponent(jTextFieldAE, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Turno)
                            .addGap(27, 27, 27)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(Fecha)
                            .addGap(17, 17, 17)
                            .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(HoraEntrada)
                            .addGap(7, 7, 7)
                            .addComponent(jTextFieldHentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(HoraSalida)
                            .addGap(5, 5, 5)
                            .addComponent(jTextFieldHsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jButtonCerrar)
                            .addGap(298, 298, 298)
                            .addComponent(Guardar)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Title)
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NEmpleado)
                        .addComponent(jTextFieldNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AEmpleado)
                        .addComponent(jTextFieldAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Turno)
                        .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Fecha)
                        .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HoraEntrada)
                        .addComponent(jTextFieldHentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HoraSalida)
                        .addComponent(jTextFieldHsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(98, 98, 98)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonCerrar)
                        .addComponent(Guardar))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTurnoActionPerformed
        String selectedItem = (String) jComboBoxTurno.getSelectedItem();
        if (selectedItem != null && !selectedItem.trim().isEmpty()) {
            jComboBoxTurno.removeItem("");
        }

    }//GEN-LAST:event_jComboBoxTurnoActionPerformed

    private void jTextFieldHentradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHentradaMousePressed
        if(jTextFieldFecha.getText().isEmpty()){
            jTextFieldFecha.setText("dd/mm/aaaa");
            jTextFieldFecha.setForeground(Color.gray);
        }
        if(jTextFieldHentrada.getText().equals("00:00")){
            jTextFieldHentrada.setText("");
            jTextFieldHentrada.setForeground(Color.black);
        }
        if(jTextFieldHsalida.getText().isEmpty()){
            jTextFieldHsalida.setText("00:00");
            jTextFieldHsalida.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldHentradaMousePressed

    private void jTextFieldHsalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldHsalidaMousePressed
        if(jTextFieldFecha.getText().isEmpty()){
            jTextFieldFecha.setText("dd/mm/aaaa");
            jTextFieldFecha.setForeground(Color.gray);
        }
        if(jTextFieldHentrada.getText().isEmpty()){
            jTextFieldHentrada.setText("00:00");
            jTextFieldHentrada.setForeground(Color.gray);
        }
        if(jTextFieldHsalida.getText().equals("00:00")){
            jTextFieldHsalida.setText("");
            jTextFieldHsalida.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldHsalidaMousePressed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        nombreEmpleado = jTextFieldNE.getText().trim();
        apellidoEmpleado = jTextFieldAE.getText().trim();
        fecha = jTextFieldFecha.getText().trim();
        turno = (String) jComboBoxTurno.getSelectedItem();
        horaEntrada = jTextFieldHentrada.getText().trim();
        horaSalida = jTextFieldHsalida.getText().trim();

        StringBuilder mensajeError = new StringBuilder();
        if (nombreEmpleado.isEmpty()) mensajeError.append("Falta ingresar el nombre.\n");
        if (apellidoEmpleado.isEmpty()) mensajeError.append("Falta ingrsar el apellido.\n");
        if (fecha.isEmpty()) mensajeError.append("Falta ingresar la fecha.\n");
        if (turno == null || turno.trim().isEmpty()) mensajeError.append("Falta seleccionar un turno.\n");
        if (horaEntrada.isEmpty()) mensajeError.append("Falta ingresar la hora de Entrada.\n");
        if (horaSalida.isEmpty()) mensajeError.append("Falta ingresar la hora de Salida.\n");

        if (mensajeError.length() > 0) {
            JOptionPane.showMessageDialog(
                rootPane,
                mensajeError.toString(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        g_A_asistencias nuevaAsistencia = new g_A_asistencias();
        nuevaAsistencia.setNombreEmpleado(jTextFieldNE.getText());
        nuevaAsistencia.setApellidoEmpleado(jTextFieldAE.getText());
        nuevaAsistencia.setFecha(jTextFieldFecha.getText());
        nuevaAsistencia.setTurno((String)jComboBoxTurno.getSelectedItem());
        nuevaAsistencia.setHoraEntrada(jTextFieldHentrada.getText());
        nuevaAsistencia.setHoraSalida(jTextFieldHsalida.getText());
        listaAsistencias.add(nuevaAsistencia);

        JOptionPane.showMessageDialog(
            rootPane,
            "Nombre del Empleado: " + jTextFieldNE.getText() + "\n" +
            "Apellido del Empleado: " + jTextFieldAE.getText() + "\n" +
            "Fecha: " + jTextFieldFecha.getText() + "\n" +
            "Turno: " + jComboBoxTurno.getSelectedItem() + "\n" +
            "Hora de Entrada: " + jTextFieldHentrada.getText() + "\n" +
            "Hora de Salida: " + jTextFieldHsalida.getText(),
            "Información del Empleado",
            JOptionPane.INFORMATION_MESSAGE
        );

        nombreEmpleado = jTextFieldNE.getText();
        apellidoEmpleado = jTextFieldAE.getText();
        fecha = jTextFieldFecha.getText();
        turno = (String)jComboBoxTurno.getSelectedItem();
        horaEntrada = jTextFieldHentrada.getText();
        horaSalida = jTextFieldHsalida.getText();

        try{
            llenartxt();
        }catch (IOException ex){
            Logger.getLogger(g_A_asistencias.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTextFieldNE.setText(null);
        jTextFieldAE.setText(null);
        jTextFieldFecha.setText(null);
        jComboBoxTurno.setSelectedItem(null);
        jTextFieldHentrada.setText(null);
        jTextFieldHsalida.setText(null);

    }//GEN-LAST:event_GuardarActionPerformed

    private void jTextFieldFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFechaMousePressed
        if(jTextFieldFecha.getText().equals("dd/mm/aaaa")){
            jTextFieldFecha.setText("");
            jTextFieldFecha.setForeground(Color.black);
        }
        if(jTextFieldHentrada.getText().equals("00:00")){
            jTextFieldHentrada.setText("");
            jTextFieldHentrada.setForeground(Color.gray);
        }
        if(jTextFieldHsalida.getText().isEmpty()){
            jTextFieldHsalida.setText("00:00");
            jTextFieldHsalida.setForeground(Color.gray);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaMousePressed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        for (g_A_asistencias gestionAsistencias: listaAsistencias){
            System.out.println(gestionAsistencias.getNombreEmpleado() + gestionAsistencias.getApellidoEmpleado());
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(g_A_VentanaGestionAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(g_A_VentanaGestionAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(g_A_VentanaGestionAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(g_A_VentanaGestionAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new g_A_VentanaGestionAsistencias().setVisible(true);
            }
        });
    }
    
    public void llenartxt()throws IOException{
        String Linea;
        Linea = nombreEmpleado +"|"+ apellidoEmpleado +"|"+ fecha +"|"+ turno+"|"+horaEntrada+"|"+horaSalida+ "\n";
        writer = new FileWriter(File,true);
        writer.write(Linea);
        writer.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AEmpleado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel HoraEntrada;
    private javax.swing.JLabel HoraSalida;
    private javax.swing.JLabel NEmpleado;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Turno;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JTextField jTextFieldAE;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldHentrada;
    private javax.swing.JTextField jTextFieldHsalida;
    private javax.swing.JTextField jTextFieldNE;
    // End of variables declaration//GEN-END:variables
}
